[build-system]
requires = [ "setuptools>=60", "wheel", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ngsolve_gui"
dynamic = ["version"]
dependencies = [
    "ngapp>=0.4.2",
    "cerbsim_ngapp_style>=0.1.2",
    "ngsolve_webgpu>=0.5.6",
    "ngsolve",
    "numpy",
    "anywidget",
    "psutil; sys_platform != 'emscripten'",
    "requests; sys_platform != 'emscripten'",
]

[project.optional-dependencies]
gpu-monitor = ["pynvml"]
plotting = ["plotly", "matplotlib"]
interactive = ["IPython"]

[project.scripts]
ngsolve = "ngsolve_gui.run:main"
ngsolve_gui = "ngsolve_gui.run:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ngsolve_gui = ["assets/*.png"]

[tool.setuptools_scm]
version_file = "src/ngsolve_gui/_version.py"
local_scheme = "no-local-version"

